- name: printing variables from inventory defined
  hosts: local
  connection: local

  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "Hi, Course name: {{ COURSE }}, Durations is: {{ DURATION }}, Trainer name: {{ TRAINER }}"