- name: functions
  hosts: local
  connection: local

  vars: 
    technologies: Ansible, Shell, DevOps, Linux, AWS #String vars
    name: "Raja Shekar p"

    #dictionary == map

    tags:
      Application: roboshop
      Environment: Dev

    listTags:
    - key: Application
      value: roboshop
    - key: Environment
      value: Dev


  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hi, {{ name | default ('Rajashekar')}} "

  - name: string vars into list
    ansible.builtin.debug:
      msg: "Hi, {{ technologies | split(',')}}"

  - name: data like dictionary or map into list
    ansible.builtin.debug:
      msg: "Hi, tag list is: {{ tags | dict2items }}"

  - name: data list into map or dictionary
    ansible.builtin.debug:
      msg: "Hi, listed tags are: {{ listTags | items2dict }}"

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  # - name: show student data
  #   ansible.builtin.debug:
  #     msg: " Hi, student data is: {{ student_yaml | to_json }}"

  - name: copy data to a file
    ansible.builtin.copy:
      content: "{{ student_yaml | to_nice_json }}"
      dest: ./student-data.json

  - name: convert to uppercase
    ansible.builtin.debug:
      msg: "Hi, {{name | upper}} "
      



